# https://taskfile.dev

version: '3'

silent: true

tasks:
  load-dependencies:
    desc: Install all dependencies
    cmds:
      #- go mod init github.com/thetillhoff/temingo # only required once per repository
      - go get -v -u ./... # also updates existing packages

  clean-dependencies:
    desc: Tidy & update all dependencies in go.mod and go.sum
    cmds:
      - go mod tidy

  build:
    desc: Build executable for current OS
    cmds:
      - go build temingo.go
      - task: clean-dependencies
